.Dd June 26, 2026
.Dt BDEMOUNT 1
.Os
.Sh NAME
.Nm bdemount
.Nd mounts a BitLocker Drive Encrypted (BDE) volume
.Sh SYNOPSIS
.Nm bdemount
.Op Fl k Ar keys
.Op Fl o Ar offset
.Op Fl p Ar password
.Op Fl r Ar recovery_password
.Op Fl s Ar startup_key_path
.Op Fl X Ar extended_options
.Op Fl huvV
.Ar source
.Ar mount_point
.Sh DESCRIPTION
.Nm bdemount
is a utility to mount a BitLocker Drive Encrypted (BDE) volume
.Pp
.Nm bdemount
is part of the
.Nm libbde
package.
.Nm libbde
is a library to access the BitLocker Drive Encryption (BDE) format
.Pp
.Ar source
a BitLocker Drive Encrypted (BDE) volume
.Ar mount_point
the directory to serve as mount point
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl k Ar keys
specify the full volume encryption key and tweak key formatted in base16 and \
separated by a : character e.g. FVEK:TWEAK
.It Fl o Ar offset
specify the volume offset in bytes
.It Fl p Ar password
specify the password (or passphrase)
.It Fl r Ar recovery_password
specify the recovery password (or passphrase)
.It Fl s Ar startup_key_path
specify the path of the file containing the startup key.
Typically this file has the extension .BEK
.It Fl u
unattended mode (disables user interaction)
.It Fl v
verbose output to stderr, while bdemount will remain running in the foreground
.It Fl V
print version
.It Fl X Ar extended_options
extended options to pass to sub system
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# bdemount -p Password /dev/sda1
bdemount 20110821
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh SEE ALSO
.Xr bdeinfo 1
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libbde/issues
.Sh COPYRIGHT
Copyright (C) 2011-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
