Document: libbde
Title: Debian libbde Manual
Author: <insert document author here>
Abstract: This manual describes what libbde is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libbde/libbde.sgml.gz

Format: postscript
Files: /usr/share/doc/libbde/libbde.ps.gz

Format: text
Files: /usr/share/doc/libbde/libbde.text.gz

Format: HTML
Index: /usr/share/doc/libbde/html/index.html
Files: /usr/share/doc/libbde/html/*.html
